FE/FE/urls.py
from .views import (
    home,
    fog,
    community,
    contact,
    forgot_id,
    forgot_pw,
    signup,
    post_form,
    support,
    about_us,
    news_list,
    news_detail,
    user_profile,
    admin_profile,
    contact_list,
    contact_list_category,
    contact_detail,
    submit_contact,
    delete_contact,
    create_post,
    n_category_news_list,
    create_comment,
    delete_comment,
    get_progress,
    like_newspost,
    dislike_newspost,
    delete_post,
    edit_post_view,
    edit_post_text,

    # fog_result,   모델 만들어지면 예정
    review_detail,
    
    forgot_id_result,
    user_login,
    user_logout,
    support_detail,
    # change_profile_info,
    # change_profile_picture,
)
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", home, name="home"),
    path("community", community, name="community"),
    path("contact", contact, name="contact"),
    path("post_form", post_form, name="post_form"),
    path("support", support, name="support"),
    path("support_detail/<int:post_num>/", support_detail, name="support_detail"),
    path("review_detail", review_detail, name="review_detail"),
    path("news_list", news_list, name="news_list"),

        # --- 회원관련 ---
    path("about_us", about_us, name="about_us"),
    path("id_res", forgot_id_result, name="forgot_id_result"),
    path("user_login", user_login, name="user_login"),
    path("user_logout", user_logout, name="user_logout"),
    path("forgot_id", forgot_id, name="forgot_id"),
    path("forgot_id_result", forgot_id_result, name="forgot_id_result"),
    path("forgot_pw", forgot_pw, name="forgot_pw"),
    path("signup", signup, name="signup"),
    path("user_profile", user_profile, name="user_profile"),
    path("admin_profile", admin_profile, name="admin_profile"),
    # path("change_profile_picture", change_profile_picture, name="change_profile_picture"),
    # path("change_profile_info", change_profile_info, name="change_profile_info"),
    # --- fog ---
    path("fog/", fog, name="fog"),
    path('get_progress/', get_progress, name='get_progress'),

# ========================== contact BE url ===============================
    path('submit_contact', submit_contact, name='submit_contact'),
    path("contact_list", contact_list, name="contact_list"),
    path("contact_list/<str:category>/", contact_list_category, name="contact_list_category"),
    path("contact_detail/<int:post_num>/", contact_detail, name="contact_detail"),
    path("delete_contact", delete_contact, name="delete_contact"),
    path("create_post", create_post, name="create_post"),
    path("news_list/<str:n_category>/", n_category_news_list, name="news_list_category"),
    path("news_detail/<int:post_num>/", news_detail, name="news_detail"),
    path("create_comment/<int:post_num>/", create_comment, name="create_comment"),
    path("delete_comment/<int:post_num>/<int:comment_id>/", delete_comment, name="delete_comment"),
    path("like_newspost/<int:pk>/",like_newspost, name="like_newspost"),
    path("dislike_newspost/<int:pk>/",dislike_newspost, name="dislike_newspost"),
    path("delete/<int:pk>/",delete_post, name="delete_post"),
    path("edit_post_view/<int:pk>/",edit_post_view, name="edit_post_view"),
    path("edit_post_text/<int:pk>/",edit_post_text, name="edit_post_text"),
    # path("fog_result", fog_result, name="fog_result"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FE/finalProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include  #new
from django.conf import settings
from FE.views import page_not_found
from django.conf.urls import handler404

handler404 = page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("FE.urls"))  #new 
] 

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

FE/FE/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# --- 회원 관련 ---

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_message  = models.TextField()
    git_address = models.URLField(max_length=30, default='')
    profile_picture = models.ImageField(upload_to='profile/', default='profile/default.jpg')
    dateTimeOfUpload = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

# --- fog 관련 model ---

class UploadedFile(models.Model):
    file = models.FileField(upload_to='after_fog/')
    upload_date = models.DateTimeField(auto_now_add=True)
    
class dehazing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_image = models.ImageField(upload_to='before_fog/')
    processed_image = models.ImageField(upload_to='after_fog/', null=True, blank=True)
    # original_video = models.FileField(upload_to='before_fog/')
    # processed_video = models.FileField(upload_to='after_fog/', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

# --- contact 모델 ---
class ContactMessage(models.Model):
    post_num = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50, default='normal')


    def __str__(self):
        return f"{self.title}"

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

class PostForm(models.Model):
    post_num = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    img = models.ImageField(upload_to='img', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50, default='normal')
    likes = models.ManyToManyField(User, related_name="likes", blank=True)
    dislikes = models.ManyToManyField(User, related_name="dislikes", blank=True)
    def __str__(self):
        return f"{self.title}"

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(PostForm, on_delete=models.CASCADE)
    parentcomment = models.ForeignKey('self',on_delete=models.CASCADE, null=True, related_name='replies')
    is_reply = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.content}"
    class Meta:
        ordering = ["-created_at"]

FE/templates/pages/admin/admin-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .support,
    .news,
    .contact {
      width: 300px;
    }
    
    span a,
    h2 a {
      color: #7395ae;
    }
    
    span a:hover,
    h2 a:hover {
      color: var(--color-fg);
    }
    
    .accordion-button:not(.collapsed) {
      background-color: #becdd9;
      color: white;
    }
    
    .admin-box h1 {
      margin-bottom: 1rem;
    }
  </style>
  <div class="container">
    <div class="container my-5">
      <div class="row">
        <!-- 백엔드: 좌측 상단 프로필 이미지 -->
        <div class="col text-center">
          <div>
            <h5>{{request.user.last_name}}님! 프로필 사진을 바꾸려면 사진을 클릭하세요.</h5>
            <div>
              <img src="{{ profile.profile_picture.url }}" id="profile-image-preview" class="rounded-circle profile-image" 
              alt="{{ profile.user.username }}" width="300" height="300" 
              onclick="document.getElementById('id_profile_picture').click();" />
            </div>
            <div>
              <form method="post" enctype="multipart/form-data" id="profile-picture-form">
                {% csrf_token %}
                <input type="file" name="profile_picture" id="id_profile_picture" style="display: none;" onchange="previewImage(this);">
              </form>
            </div>
          </div>
        </div>
        <!-- '하루 접속자 수', '하루 작성된 리뷰 수', '하루 서비스 이용자 수'를 표시하는 박스 -->
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">통계 정보</h5>
              <ul class="list-group">
                <li class="list-group-item">오늘 접속자 수: {{ daily_visitors }}명</li>
                <li class="list-group-item">오늘/누적 작성된 문의 수: {{ daily_contacts }}개 / {{total_contacts}}개</li>
                <li class="list-group-item">오늘/누적 작성된 리뷰 수: {{ daily_reviews }}개 / {{total_contacts}}개</li>
                <li class="list-group-item">오늘/누적 서비스 이용 수: {{ daily_users }}회 / {{ total_users }}회</li>
              </ul>
            </div>
            <div class="card-body profile-box">
              <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                  <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" 
                    data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                      프로필 수정
                    </button>
                  </h2>
                  <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                    <form method="post" action="{% url 'admin_profile' %}" id="profile-info-form">
                      <div>
                        <!-- 이부분 css 수정원하시면 forms.py에 주석 표시했읍니다 -->
                        <p class="mt-2" for="id_profile_message">{{ profile_info_form.profile_message.label }} {{ profile_info_form.profile_message }}</p>
                      </div>
                      <div>
                        <p for="id_git_address">{{ profile_info_form.git_address.label }} {{ profile_info_form.git_address }}</p>
                      </div>
                      <button class="btn btn-primary rounded-pill" type="submit" name="form_type" value="profile_info_form">Submit</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 'support.html', 'community-news.html', 'contact-list'로 넘어가는 박스 -->
    <div class="row justify-content-evenly">
      <div id="admin-resources" class="support p-4 text-center justify-content-center border border-light-subtle border-1 rounded">
        <div class="admin-box text-center col-md-4 mb-5">
          <h1>Reviews</h1>
        </div>
        <div style="text-align: left;" class="mb-4">
          {% for support in recent_supports %}
            <div>
              <span class="date">{{ support.created_at|date:"Y-m-d H:i" }}</span>
              <h2><a href="{% url 'support_detail' support.post_num %}">{{ support.title }}</a></h2>
            </div>
          {% empty %}
            <p> 리뷰 없음. </p>
          {% endfor %}
        </div>
        <a href="{% url 'support' %}" class="btn btn-primary btn-block">더보기</a>
</div>
      <div id="admin-resources" class="news p-4 text-center border border-light-subtle border-1 rounded">
        <div class="admin-box text-center col-md-4 mb-5">
          <h1>News</h1>
        </div>
        <div style="text-align: left;" class="mb-4">
          {% for news in recent_news %}
            <div>
              <span class="date">{{ news.created_at|date:"Y-m-d H:i" }}</span>
              <h2><a href="{% url 'news_detail' news.post_num %}">{{ news.title }}</a></h2>
            </div>
          {% empty %}
            <p> 뉴스 없음. </p>
          {% endfor %}
        </div>
        <a href="{% url 'news_list' %}" class="btn btn-primary btn-block">더보기</a>
      </div>

      <div id="admin-resources" class="contact p-4 text-center border border-light-subtle border-1 rounded">
        <div class="admin-box text-center col-md-4 mb-5">
          <h1>Contact</h1>
        </div>
        <div style="text-align: left;" class="mb-4">
          {% for contact in recent_contacts %}
            <div>
              <span class="date">{{ contact.created_at|date:"Y-m-d H:i" }}</span>
              <h2><a href="{% url 'contact_detail' contact.post_num %}">{{ contact.title }}</a></h2>
            </div>
          {% empty %}
            <p> 문의 없음. </p>
          {% endfor %}
        </div>
        <a href="{% url 'contact_list' %}" class="btn btn-primary btn-block">더보기</a>
      </div>
    </div>

  <script>
    function previewImage(input) {
      if (input.files && input.files[0]) {
        var form = document.getElementById('profile-picture-form');
        form.submit();
      }
    }
  </script>

  <script>      //프로필사진 업로드 버튼 없이 바로 바뀌게 하려고 넣음
    function previewImage(input) {
      if (input.files && input.files[0]) {
        input.form.submit();
      }
    }
  </script>

{% endblock %}

FE/templates/pages/admin/support.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link href="{% static 'css/support.css' %}" rel="stylesheet" />

  
  <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container text-center py-5">
      <h1 class="display-2 text-dark mb-4 animated slideInDown">Support</h1>
    </div>
  </div>
  <div class="container content-support">
    <div class="row">
      <!-- 좌측 상단 '질문하기' 버튼 -->
      <div class="col-md-2">
        <!-- 백엔드: '질문하기' 버튼 -->
        <a href="{% url 'post_form' %}" class="btn btn-primary">글쓰기</a>
      </div>
      <!-- 우측 상단 '검색' 입력란 -->
              <div class="col d-flex justify-content-end">
          <form action="#" class="sidebar-search-form d-sm-inline-flex flex-row-reverse">
            <form action="{% url 'contact_list' %}" method="GET" id="BoardSearch" name="BoardSearch">
              <input type="hidden" id="contact_kw" name="contact_kw" value="{{ contact_kw|default_if_none:'' }}" />
              <input type="hidden" id="page" name="page" value="{{ page }}" />
            </form>
            <div class="navbar-nav align-items-center mx-1">
              <div class="nav-item d-flex align-items-center" style="width:100%;">
                <input type="text" class="form-control border-1 shadow-none" placeholder="게시글 검색" aria-label="Search..." id="contact_search_kw" name="contact_search_kw" value="{{ contact_search_kw|default_if_none:'' }}" />
              </div>
            </div>
            <div style="list-style:none;">
              <button class="btn btn-primary" type="button" id="btnSearch" aria-label="buttonForSearch"><i class="fas fa-search"></i></button>
            </div>
          </form>
        </div>

    </div>
 

    <div class="row">
      <!-- '네비' (카테고리 선택) -->
      <div class="col-md-12 my-4">
        <!-- 백엔드: 카테고리 네비게이션 -->
        <ul class="nav">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'support' %}">전체</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news_list_category' n_category='normal' %}">일반</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news_list_category' n_category='question' %}">질문</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news_list_category' n_category='use' %}">제품사용</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news_list_category' n_category='preview' %}">시연</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news_list_category' n_category='etc' %}">기타</a>
              </li>
            </ul>
      </div>
    </div>


  <section class="main-post-section">
    {% comment %}for{% endcomment %}
    <div class="row container content-center posts-entry">
        {% csrf_token %}
        {% for newspost in newsposts %}
          <div class="col-12">
            <div class="blog-entry d-flex justify-content-between blog-entry-search-item mb-5">
              <div>
                <span class="date">{{ newspost.created_at }} <a href="#">{{ newspost.category }}</a></span>
                <h2><a href="{% url 'news_detail' post_num=newspost.post_num %}">{{ newspost.title }}</a></h2>
                <p>{{ newspost.text }}</p>
              </div>
              <div >
              <form action="{% url 'delete_post' pk=newspost.post_num %}" class="d-flex justify-content-end">
              {% csrf_token %}
              <div class="menu">
              <div class="msg-delete-btn inline-block justify-content-end text-end ms-auto">
                <input type="submit" value="DELETE" class="btn btn-danger" />
              </div>
            </div>
            </form>
          </div>
            </div>
          </div>
      </div>
      {% endfor %}
  </div>
</section>

<section class="pagination-section">
  {% if newsposts.paginator.num_pages >= 1 %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if newsposts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ newsposts.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}

      {% for num in newsposts.paginator.page_range %}
        <li class="page-item {% if num == newsposts.number %}active{% endif %}">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endfor %}

      {% if newsposts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ newsposts.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</section>
{% endblock %}